name: CSV Lint workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install goodtables
    - name: Run csv-lint
      run: goodtables $GITHUB_WORKSPACE/breweries.csv
